/**
 * Authentication Helper Functions
 */

const crypto = require('crypto');
const geoip = require('geoip-lite');

const helpers = {
  /**
   * Generate random token/ID with custom length (reusable)
   * @param {number} length - Length of the token in bytes (will be hex, so double the length)
   * @returns {string} - Random hex string
   * @example
   * generateRandomToken(4)  // Returns 8-char hex string like "a1b2c3d4"
   * generateRandomToken(32) // Returns 64-char hex string for session tokens
   */
  generateRandomToken: (length = 32) => {
    return crypto.randomBytes(length).toString('hex');
  },

  /**
   * Validate user account status - check if allowed to login
   * @param {string} status - User status from DB
   * @returns {object} - { allowed: boolean, message: string }
   */
  validateAccountStatus: (status) => {
    const allowedStatuses = ['active', 'pending', 'inreview'];
    const isAllowed = allowedStatuses.includes(status);
    
    let message = '';
    if (status === 'suspended') {
      message = 'Your account has been suspended';
    } else if (status === 'deleted') {
      message = 'Your account has been deleted';
    } else if (status === 'inactive') {
      message = 'Your account is inactive';
    }

    return {
      allowed: isAllowed,
      message: message,
      status: status
    };
  },

  /**
   * Generate unique 8-digit numeric referral code
   * @param {object} client - Database client for uniqueness check
   * @returns {Promise<string>} - 8-digit referral code
   */
  generateUniqueReferralCode: async (client) => {
    const MAX_RETRIES = 10;
    let attempts = 0;

    while (attempts < MAX_RETRIES) {
      const referralCode = Math.floor(10000000 + Math.random() * 90000000).toString();
      
      // Check if referral code is unique
      const existingCode = await client.query(
        'SELECT pid FROM user_profiles WHERE referral_code = $1',
        [referralCode]
      );
      
      if (existingCode.rows.length === 0) {
        return referralCode;
      }
      attempts++;
    }

    throw new Error('Failed to generate unique referral code after maximum retries');
  },

  /**
   * Generate a 6-digit OTP
   */
  generateOTP: () => {
    return Math.floor(100000 + Math.random() * 900000).toString();
  },

  /**
   * Generate a session token (secure random 64 hex chars)
   */
  generateSessionToken: () => {
    return helpers.generateRandomToken(32); // 32 bytes = 64 hex chars
  },

  /**
   * Generate a refresh token (secure random 16 hex chars)
   */
  generateRefreshToken: () => {
    return helpers.generateRandomToken(8); // 8 bytes = 16 hex chars
  },

  /**
   * Generate a unique user ID (UID) - 18 hex chars (auto-generated by DB, but can generate locally too)
   * Database: generate_alphanum_id(18) in users table
   */
  generateUID: () => {
    return helpers.generateRandomToken(9); // 9 bytes = 18 hex chars
  },

  /**
   * Generate a verification token (18 bytes hex)
   */
  generateVerificationToken: () => {
    return crypto.randomBytes(18).toString('hex');
  },

  /**
   * Generate device fingerprint from user agent and other device info
   * @param {string} userAgent - User agent string
   * @param {object} deviceInfo - Additional device information
   * @returns {string} - Device fingerprint hash
   */
  generateDeviceFingerprint: (userAgent = '', deviceInfo = {}) => {
    const fingerprintData = {
      userAgent: userAgent || 'unknown',
      screenResolution: deviceInfo.screenResolution || 'unknown',
      timezone: deviceInfo.timezone || (() => { try { return Intl.DateTimeFormat().resolvedOptions().timeZone; } catch { return 'UTC'; } })(),
      language: deviceInfo.language || 'unknown',
      platform: deviceInfo.platform || 'unknown',
      vendor: deviceInfo.vendor || 'unknown',
      hardwareConcurrency: deviceInfo.hardwareConcurrency || 'unknown',
      deviceMemory: deviceInfo.deviceMemory || 'unknown'
    };
    
    const fingerprintString = JSON.stringify(fingerprintData);
    return crypto.createHash('sha256').update(fingerprintString).digest('hex');
  },

  /**
   * Get geolocation from IP address
   * @param {string} ipAddress - IP address to geolocate
   * @returns {object} - Geolocation data {country, city, latitude, longitude, timezone}
   */
  getLocationFromIP: (ipAddress = '') => {
    try {
      if (!ipAddress || ipAddress === 'unknown' || ipAddress === 'localhost' || ipAddress === '127.0.0.1') {
        return { country: null, city: null, latitude: null, longitude: null, timezone: null };
      }

      const geo = geoip.lookup(ipAddress);
      
      if (!geo) {
        return { country: null, city: null, latitude: null, longitude: null, timezone: null };
      }

      return {
        country: geo.country || null,
        city: geo.city || null,
        timezone: geo.timezone || null,
        latitude: geo.ll ? geo.ll[0] : null,    // Array format: [latitude, longitude]
        longitude: geo.ll ? geo.ll[1] : null
      };
    } catch (error) {
      console.error('[GEOIP_ERROR]', error.message);
      return { country: null, city: null, latitude: null, longitude: null, timezone: null };
    }
  },

  /**
   * Extract device info from request
   * @param {object} req - Express request object
   * @param {object} clientDeviceInfo - Optional device info from client
   * @returns {object} - Device information
   */
  extractDeviceInfo: (req, clientDeviceInfo = {}) => {
    const userAgent = req.get('user-agent') || 'unknown';
    const ipAddress = req.ip || req.socket?.remoteAddress || 'unknown';
    
    // Get location from IP if not provided by client
    const ipGeoLocation = helpers.getLocationFromIP(ipAddress);
    const clientLocation = clientDeviceInfo.location || ipGeoLocation.city;
    const clientLatitude = clientDeviceInfo.latitude !== undefined ? clientDeviceInfo.latitude : ipGeoLocation.latitude;
    const clientLongitude = clientDeviceInfo.longitude !== undefined ? clientDeviceInfo.longitude : ipGeoLocation.longitude;
    
    // Generate device fingerprint with fallback for safety (BUG FIX #7)
    const generatedFingerprint = helpers.generateDeviceFingerprint(userAgent, clientDeviceInfo);
    const deviceFingerprint = generatedFingerprint || helpers.generateDeviceFingerprint('unknown', {});
    
    return {
      ip_address: ipAddress,
      user_agent: userAgent,
      device_fingerprint: deviceFingerprint,
      device_name: clientDeviceInfo.deviceName || null,
      os_type: clientDeviceInfo.osType || null,
      browser_type: clientDeviceInfo.browserType || null,
      location: clientLocation,
      latitude: clientLatitude,
      longitude: clientLongitude,
      country: ipGeoLocation.country,
      timezone: ipGeoLocation.timezone || clientDeviceInfo.timezone || null,
      device_memory: clientDeviceInfo.deviceMemory || null,
      screen_resolution: clientDeviceInfo.screenResolution || null
    };
  },

  /**
   * Validate phone number format - Indian phone numbers only (exactly 10 digits)
   */
  validatePhone: (phone) => {
    const phoneRegex = /^[0-9]{10}$/;
    return phoneRegex.test(phone.replace(/\D/g, ''));
  },

  /**
   * Validate email format
   */
  validateEmail: (email) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  },

  /**
   * Validate gender
   */
  validateGender: (gender) => {
    const validGenders = ['male', 'female', 'other', 'prefer_not_to_say'];
    return validGenders.includes(gender.toLowerCase());
  },

  /**
   * Validate date format (YYYY-MM-DD)
   */
  validateDateFormat: (date) => {
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    return dateRegex.test(date);
  },

  /**
   * Clean phone number (remove non-digits)
   */
  cleanPhone: (phone) => {
    return phone.replace(/\D/g, '');
  },

  /**
   * Validate session token and get user ID
   * @param {object} client - Database client
   * @param {string} token - Session token from Authorization header
   * @returns {Promise<string|null>} - User ID if valid, null if invalid/expired
   */
  validateSessionToken: async (client, token) => {
    try {
      // BUG FIX #11: Add parameter validation before querying
      if (!token || !client) {
        console.warn('[SESSION_VALIDATION_WARNING]', 'Missing token or client');
        return null;
      }

      const result = await client.query(
        'SELECT uid FROM sessions WHERE session_token = $1 AND status = $2 AND expires_at > NOW()',
        [token, 'active']
      );
      return result.rows.length > 0 ? result.rows[0].uid : null;
    } catch (error) {
      // BUG FIX #11: Log error details for debugging
      console.error('[SESSION_VALIDATION_ERROR]', {
        timestamp: new Date().toISOString(),
        errorMessage: error.message,
        errorCode: error.code,
        errorDetail: error.detail
      });
      return null;
    }
  },

  /**
   * Create a session in the database (used inside transaction)
   * BUG FIX #2: CRITICAL - Properly throw errors so transaction can rollback
   * @param {object} client - Database transaction client
   * @param {string} userId - User ID
   * @param {object} deviceInfo - Device information object
   * @returns {object} - { sessionToken, refreshToken }
   * @throws {Error} - If session creation fails (allows transaction rollback)
   */
  createUserSession: async (client, userId, deviceInfo) => {
    const sessionToken = helpers.generateSessionToken();
    const refreshToken = helpers.generateRefreshToken();
    const sessionExpirationDays = parseInt(process.env.SESSION_EXPIRATION_DAYS, 10) || 7;
    const sessionExpires = new Date(Date.now() + sessionExpirationDays * 24 * 60 * 60 * 1000);

    try {
      await client.query(
        `INSERT INTO sessions (uid, session_token, refresh_token, device_name, device_fingerprint, os_type, browser_type, ip_address, user_agent, location, latitude, longitude, status, expires_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)`,
        [userId, sessionToken, refreshToken, deviceInfo.device_name, deviceInfo.device_fingerprint, deviceInfo.os_type, deviceInfo.browser_type, deviceInfo.ip_address, deviceInfo.user_agent, deviceInfo.location, deviceInfo.latitude, deviceInfo.longitude, 'active', sessionExpires]
      );
    } catch (sessionError) {
      console.error('[SESSION_CREATION_ERROR]', {
        uid: userId,
        error: sessionError.message,
        errorCode: sessionError.code,
        timestamp: new Date().toISOString()
      });
      // CRITICAL FIX: Throw error so transaction can ROLLBACK on failure
      throw new Error(`SESSION_CREATION_FAILED: ${sessionError.message}`);
    }

    return { sessionToken, refreshToken };
  }
};

module.exports = helpers;
